const employees = [
    {
        id: 1,
        name: "Андрей Богданович Витько",
        specialization: "Хирург",
        experience: "3 года",
        category: "высшая",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. A possimus excepturi aliquid nihil cumque ipsam facere aperiam at! Ea dolorem ratione sit debitis deserunt repellendus numquam ab vel perspiciatis corporis!",
        img: "https://i.pinimg.com/564x/6c/6e/d7/6c6ed7f4011b7f926b3f1505475aba16.jpg",
    },
    {
        id: 2,
        name: "Анна Витальевна Гоголь",
        specialization: "Логопед",
        experience: "25 лет",
        category: "высшая",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. A possimus excepturi aliquid nihil cumque ipsam facere aperiam at! Ea dolorem ratione sit debitis deserunt repellendus numquam ab vel perspiciatis corporis!",
        img: "https://i.pinimg.com/564x/2a/b8/ef/2ab8efe33df72c7858617dde6a723ff1.jpg",
    },
    {
        id: 3,
        name: "Николай Сергеевич Романов",
        specialization: "Кардиолог",
        experience: "10 лет",
        category: "высшая",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. A possimus excepturi aliquid nihil cumque ipsam facere aperiam at! Ea dolorem ratione sit debitis deserunt repellendus numquam ab vel perspiciatis corporis!",
        img: "https://i.pinimg.com/564x/6c/6e/d7/6c6ed7f4011b7f926b3f1505475aba16.jpg",
    },
    {
        id: 4,
        name: "Андрей Николаевич Приходько",
        specialization: "Косметолог",
        experience: "3 года",
        category: "высшая",
        desc: "A possimus excepturi aliquid nihil cumque ipsam facere aperiam at! Ea dolorem ratione sit debitis deserunt repellendus numquam ab vel perspiciatis corporis!",
        img: "https://i.pinimg.com/564x/2a/b8/ef/2ab8efe33df72c7858617dde6a723ff1.jpg",
    },
    {
        id: 5,
        name: "Андрей Богданович Витько",
        specialization: "Хирург",
        experience: "5 лет",
        category: "высшая",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
        img: "https://i.pinimg.com/564x/6c/6e/d7/6c6ed7f4011b7f926b3f1505475aba16.jpg",
    },
    {
        id: 6,
        name: "Анна Витальевна Гоголь",
        specialization: "Логопед",
        experience: "8 лет",
        category: "высшая",
        desc: "Ea dolorem ratione sit debitis deserunt repellendus numquam ab vel perspiciatis corporis!",
        img: "https://i.pinimg.com/564x/2a/b8/ef/2ab8efe33df72c7858617dde6a723ff1.jpg",
    },
    {
        id: 7,
        name: "Николай Сергеевич Романов",
        specialization: "Кардиолог",
        experience: "21 год",
        category: "высшая",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. A possimus excepturi aliquid nihil cumque ipsam facere aperiam at! Ea dolorem ratione sit debitis deserunt repellendus numquam ab vel perspiciatis corporis!",
        img: "https://i.pinimg.com/564x/6c/6e/d7/6c6ed7f4011b7f926b3f1505475aba16.jpg",
    },
    {
        id: 8,
        name: "Андрей Николаевич Приходько",
        specialization: "Косметолог",
        experience: "15 лет",
        category: "высшая",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. A possimus excepturi aliquid nihil cumque ipsam facere aperiam at! Ea dolorem ratione sit debitis deserunt repellendus numquam ab vel perspiciatis corporis!",
        img: "https://i.pinimg.com/564x/2a/b8/ef/2ab8efe33df72c7858617dde6a723ff1.jpg",
    },
];


const articles = [
    {
        id: 1,
        img: "https://i.pinimg.com/564x/46/8d/60/468d60cbc6b1f88e1c140b6bfba777d1.jpg",
        tag: "Здоровье",
        duration: "5 минут чтения",
        title: "Важность регулярных физических упражнений",
        desc: "Узнайте, как регулярные физические упражнения могут улучшить ваше общее состояние здоровья.",
    },
    {
        id: 1,
        img: "https://i.pinimg.com/564x/f3/0b/c7/f30bc7914c199647e965c3539a59ba46.jpg",
        tag: "Питание",
        duration: "3 минуты чтения",
        title: "Здоровые пищевые привычки для сбалансированного питания",
        desc: "Откройте для себя важность здорового питания для сбалансированного образа жизни.",
    },
    {
        id: 1,
        img: "https://i.pinimg.com/564x/f9/38/f5/f938f5e98cdaa07acd92f2ed3a8be915.jpg",
        tag: "Психология",
        duration: "7 минут чтения",
        title: "Советы по управлению стрессом и тревогой",
        desc: "Изучите эффективные стратегии управления стрессом и тревогой.",
    },
    {
        id: 1,
        img: "https://i.pinimg.com/564x/46/8d/60/468d60cbc6b1f88e1c140b6bfba777d1.jpg",
        tag: "Здоровье",
        duration: "5 минут чтения",
        title: "Важность регулярных физических упражнений",
        desc: "Узнайте, как регулярные физические упражнения могут улучшить ваше общее состояние здоровья.",
    },
    {
        id: 1,
        img: "https://i.pinimg.com/564x/46/8d/60/468d60cbc6b1f88e1c140b6bfba777d1.jpg",
        tag: "Здоровье",
        duration: "5 минут чтения",
        title: "Важность регулярных физических упражнений",
        desc: "Узнайте, как регулярные физические упражнения могут улучшить ваше общее состояние здоровья.",
    },
    {
        id: 1,
        img: "https://i.pinimg.com/564x/46/8d/60/468d60cbc6b1f88e1c140b6bfba777d1.jpg",
        tag: "Здоровье",
        duration: "5 минут чтения",
        title: "Важность регулярных физических упражнений",
        desc: "Узнайте, как регулярные физические упражнения могут улучшить ваше общее состояние здоровья.",
    },
];

const feedback = [
    {
        id: 1,
        date: "10.06.23",
        author: "test author",
        doctorId: 1,
        text: "test text",
    },
    {
        id: 2,
        date: "02.06.23",
        author: "test author",
        doctorId: 2,
        text: "test text",
    },
    {
        id: 3,
        date: "23.06.23",
        author: "test author",
        doctorId: 3,
        text: "test text",
    },
    {
        id: 4,
        date: "08.06.23",
        author: "test author",
        doctorId: 1,
        text: "test text",
    },
]


export { employees, articles, feedback };